# Generated by Django 4.2.18 on 2025-01-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='Подписан ли текущий пользователь на этого'),
        ),
    ]
