# Generated by Django 4.2.18 on 2025-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Введите свой адрес электронной почты', max_length=254, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
