# Generated by Django 4.2.18 on 2025-01-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_is_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, help_text='Введите свое имя', max_length=150, null=True, verbose_name='Имя'),
        ),
    ]
