# Generated by Django 4.2.18 on 2025-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text='Введите свою фамилию', max_length=150, null=True, verbose_name='Фамилия'),
        ),
    ]
