# Generated by Django 4.2.18 on 2025-01-31 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=11, help_text='Введите свое имя', max_length=150, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Введите свою фамилию', max_length=150, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
