version: '3.3'

volumes:
  postgres_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend/foodgram_backend
    # image: dimanikolaev/foodgram_backend:latest
    restart: always
    volumes:
      - static:/collected_static/
      - media:/app/media/
    depends_on:
      - db
    env_file: .env

  frontend:
    build: ./frontend
    # image: dimanikolaev/foodgram_frontend:latest
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    build: ./nginx
    # image: dimanikolaev/foodgram_gateway:latest
    container_name: foodgram-proxy
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
    restart: always
    depends_on:
      - backend
      - frontend

