###
POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Завтррак",
  "slug": "breakfast"
}
###
POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Обед",
  "slug": "lunch"
}
###

POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Полдник",
  "slug": "afternoon"
}
###

POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Ужин",
  "slug": "dinner"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "огурец",
  "measurement_unit": "4"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "банан",
  "measurement_unit": "4"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "яблоко",
  "measurement_unit": "4"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "морковь",
  "measurement_unit": "4"
}
###