# Создаем набор тегов.
# не забудь сперва закоммитить строку http_method_names в TagsViewSet
###
POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Завтррак",
  "slug": "breakfast"
}
###
POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Обед",
  "slug": "lunch"
}
###

POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Полдник",
  "slug": "afternoon"
}
###

POST http://127.0.0.1:8000/api/tags/
Content-Type: application/json

{
  "name": "Ужин",
  "slug": "dinner"
}
###


# Создаем набор ингридиентов.
# не забудь сперва закоммитить строку http_method_names в IngredientsViewSet

POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "огурец",
  "measurement_unit": "кг"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "банан",
  "measurement_unit": "кг"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "яблоко",
  "measurement_unit": "кг"
}
###
POST http://127.0.0.1:8000/api/ingredients/
Content-Type: application/json

{
  "name": "морковь",
  "measurement_unit": "кг"
}
###


# Создаем пользователя.
POST http://127.0.0.1:8000/api/users/
Content-Type: application/json

{
    "email": "Dima@dima.ru",
    "username": "Dima",
    "first_name": "Вася",
    "last_name": "Иванов",
    "password": "Password1234!1"
}
###


# Получаем токен для пользователя.
POST http://127.0.0.1:8000/api/auth/token/login/
Content-Type: application/json

{
    "email": "Dima@dima.ru",
    "password": "Password1234!1"
}
###


# Записываем полученный для пользователя токен
# 5aad6bf71ca0d327f7d9e915acf2998bbc62bf89


# Создаем рецепты
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization:Token 5aad6bf71ca0d327f7d9e915acf2998bbc62bf89

{
  "ingredients": [
    {
      "id": "1",
      "amount": "2"
    },
    {
      "id": "2",
      "amount": "2"
    }
  ],
  "tags": [
    "1",
    "2"
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Нечто съедобное (это не точно)",
  "text": "Приготовьте как нибудь эти ингредиеты",
  "cooking_time": 5
}
###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization:Token 6f049cc36f4b34ac1873f7023dc573fdf3c51776

{
  "ingredients": [
    {
      "id": "2",
      "amount": "2"
    },
    {
      "id": "3",
      "amount": "2"
    }
  ],
  "tags": [
    "1",
    "2"
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Нечто съедобное (это не точно)",
  "text": "Приготовьте как нибудь эти ингредиеты",
  "cooking_time": 5
}
###
POST http://127.0.0.1:8000/api/recipes/
Content-Type: application/json
Authorization:Token 6f049cc36f4b34ac1873f7023dc573fdf3c51776

{
  "ingredients": [
    {
      "id": "3",
      "amount": "2"
    },
    {
      "id": "4",
      "amount": "2"
    }
  ],
  "tags": [
    "1",
    "2"
  ],
  "image": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg==",
  "name": "Нечто съедобное (это не точно)",
  "text": "Приготовьте как нибудь эти ингредиеты",
  "cooking_time": 5
}
###


# Проверяем рецепты
GET http://127.0.0.1:8000/api/recipes/
###


# Добавляет рецепт в список покупок пользователя
POST http://127.0.0.1:8000/api/recipes/1/shopping_cart/
Content-Type: application/json
Authorization:Token b3ff814b41f918af7e985ad6b4be9c987b3a27c5
###


# Добавляет рецепт в избранное пользователя
POST http://127.0.0.1:8000/api/recipes/3/favorite/
Content-Type: application/json
Authorization:Token b3ff814b41f918af7e985ad6b4be9c987b3a27c5
###