# Generated by Django 4.2.18 on 2025-01-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_recipetag_recipeingredient_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='api/images/', verbose_name='Картинка, закодированная в Base64'),
        ),
    ]
