# Generated by Django 4.2.18 on 2025-01-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
