# Generated by Django 4.2.18 on 2025-01-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipetag',
            old_name='tag',
            new_name='tags',
        ),
    ]
