# Generated by Django 4.2.18 on 2025-02-01 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_recipeingredient_recipe_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetag',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tag'),
        ),
    ]
