# Generated by Django 4.2.18 on 2025-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=None, help_text='Добавьте изображение рецепта', upload_to='recipes/images/', verbose_name='Картинка, закодированная в Base64'),
        ),
    ]
