# Generated by Django 4.2.18 on 2025-02-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
