# Generated by Django 4.2.18 on 2025-02-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_link',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
